import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/db'
const input=z.object({id:z.string().optional(),name:z.string().min(2).max(80),isActive:z.boolean().optional()})
const slugify=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
async function allowed(businessId:string){const session=await auth();if(!session?.user)return false;if((session.user as any).role==='SUPER_ADMIN')return true;return !!await prisma.businessMember.findFirst({where:{businessId,userId:session.user.id,role:{in:['OWNER','MANAGER','EDITOR']},status:'ACTIVE'}})}
export async function POST(req:NextRequest,{params}:{params:{businessId:string}}){try{if(!await allowed(params.businessId))return NextResponse.json({error:'No autorizado'},{status:403});const data=input.parse(await req.json());const base=slugify(data.name);let slug=base;let i=2;while(await prisma.category.findUnique({where:{businessId_slug:{businessId:params.businessId,slug}}}))slug=`${base}-${i++}`;const count=await prisma.category.count({where:{businessId:params.businessId}});const category=await prisma.category.create({data:{businessId:params.businessId,name:data.name,slug,isActive:data.isActive??true,sortOrder:count}});return NextResponse.json({category},{status:201})}catch{return NextResponse.json({error:'Datos inválidos.'},{status:400})}}
export async function PATCH(req:NextRequest,{params}:{params:{businessId:string}}){try{if(!await allowed(params.businessId))return NextResponse.json({error:'No autorizado'},{status:403});const data=input.extend({id:z.string()}).parse(await req.json());const result=await prisma.category.updateMany({where:{id:data.id,businessId:params.businessId},data:{name:data.name,isActive:data.isActive}});return result.count?NextResponse.json({ok:true}):NextResponse.json({error:'No encontrada'},{status:404})}catch{return NextResponse.json({error:'Datos inválidos.'},{status:400})}}
export async function DELETE(req:NextRequest,{params}:{params:{businessId:string}}){if(!await allowed(params.businessId))return NextResponse.json({error:'No autorizado'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Falta categoría'},{status:400});await prisma.product.updateMany({where:{businessId:params.businessId,categoryId:id},data:{categoryId:null}});const result=await prisma.category.deleteMany({where:{id,businessId:params.businessId}});return NextResponse.json({ok:!!result.count})}
