import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/db'

const schema=z.object({name:z.string().min(2).max(120),price:z.number().nonnegative(),categoryId:z.string().nullable().optional(),description:z.string().max(600).optional(),image:z.string().url().optional(),isAvailable:z.boolean().optional()})
const slugify=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
async function canManage(id:string){const session=await auth();if(!session?.user)return false;if((session.user as any).role==='SUPER_ADMIN')return true;return !!await prisma.businessMember.findFirst({where:{businessId:id,userId:session.user.id,role:{in:['OWNER','MANAGER','EDITOR']},status:'ACTIVE'}})}
export async function POST(req:NextRequest,{params}:{params:{businessId:string}}){try{if(!await canManage(params.businessId))return NextResponse.json({error:'No autorizado'},{status:403});const data=schema.parse(await req.json());const base=slugify(data.name);let slug=base;let n=2;while(await prisma.product.findUnique({where:{businessId_slug:{businessId:params.businessId,slug}}}))slug=`${base}-${n++}`;const product=await prisma.product.create({data:{...data,categoryId:data.categoryId||null,businessId:params.businessId,slug}});return NextResponse.json({product},{status:201})}catch(e){return NextResponse.json({error:e instanceof z.ZodError?'Datos inválidos.':'No fue posible crear el producto.'},{status:400})}}
export async function PATCH(req:NextRequest,{params}:{params:{businessId:string}}){try{if(!await canManage(params.businessId))return NextResponse.json({error:'No autorizado'},{status:403});const {id,...input}=z.object({id:z.string().min(1),...schema.shape}).parse(await req.json());const product=await prisma.product.updateMany({where:{id,businessId:params.businessId},data:{...input,categoryId:input.categoryId||null}});if(!product.count)return NextResponse.json({error:'Producto no encontrado'},{status:404});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:'Datos inválidos.'},{status:400})}}
export async function DELETE(req:NextRequest,{params}:{params:{businessId:string}}){if(!await canManage(params.businessId))return NextResponse.json({error:'No autorizado'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Falta el producto.'},{status:400});const deleted=await prisma.product.deleteMany({where:{id,businessId:params.businessId}});return NextResponse.json({ok:!!deleted.count})}
